// GENERATED BY moarch (`moarch create tests`). Delete this line once you edit the file, and a re-run leaves it alone.

import 'package:bloc_test/bloc_test.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';
import 'package:je_fisc/core/errors/app_exception.dart';

import 'package:je_fisc/features/category/presentation/blocs/category_bloc.dart';
import 'package:je_fisc/features/category/presentation/blocs/category_state.dart';
import 'package:je_fisc/features/category/presentation/blocs/category_event.dart';
import 'package:je_fisc/features/category/domain/repositories/category_repository.dart';
import 'package:je_fisc/features/category/domain/models/category_model.dart';

// ── Mocks ────────────────────────────────────────────────────
class MockCategoryRepository extends Mock implements CategoryRepository {}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('CategoryBloc', () {
    late MockCategoryRepository mockCategoryRepository;

    setUp(() {
      mockCategoryRepository = MockCategoryRepository();
    });

    // The class under test, wired with the mocked dependencies.
    CategoryBloc buildCategoryBloc() => CategoryBloc(mockCategoryRepository);

    test('starts in a valid initial state', () async {
      final bloc = buildCategoryBloc();
      expect(bloc.state, isA<CategoryState>());
      await bloc.close();
    });

    // ── CategoryStarted ──────────────────────────────────────
    group('CategoryStarted', () {
      blocTest<CategoryBloc, CategoryState>(
        'CategoryStarted completes successfully',
        setUp: () {
          when(
            () => mockCategoryRepository.fetchCategories(),
          ).thenAnswer((_) async => [CategoryModel.empty()]);
        },
        build: buildCategoryBloc,
        act: (bloc) => bloc.add(const CategoryStarted()),
        // Uncomment to assert the exact sequence of emitted states
        // (check the guards first — a conditional emit doesn't always run):
        // expect: () => [isA<CategoryState>()],
        verify: (bloc) {
          verify(
            () => mockCategoryRepository.fetchCategories(),
          ).called(greaterThanOrEqualTo(1));
          expect(bloc.state.errorMessage, isNull);
        },
      );

      blocTest<CategoryBloc, CategoryState>(
        'CategoryStarted surfaces an error when a dependency fails',
        setUp: () {
          // Make every dependency call this action performs
          // fail, replacing the stubs from setUp().
          when(
            () => mockCategoryRepository.fetchCategories(),
          ).thenThrow(const ServerException(message: 'test'));
        },
        build: buildCategoryBloc,
        act: (bloc) => bloc.add(const CategoryStarted()),
        verify: (bloc) {
          expect(bloc.state.errorMessage, isNotNull);
          expect(bloc.state.successMessage, isNull);
        },
      );
    });

    // ── CategoryCreated ──────────────────────────────────────
    group('CategoryCreated', () {
      blocTest<CategoryBloc, CategoryState>(
        'CategoryCreated completes successfully',
        setUp: () {
          when(
            () => mockCategoryRepository.createCategory(any()),
          ).thenAnswer((_) async => CategoryModel.empty());
          when(
            () => mockCategoryRepository.fetchCategories(),
          ).thenAnswer((_) async => [CategoryModel.empty()]);
        },
        build: buildCategoryBloc,
        act: (bloc) => bloc.add(const CategoryCreated('')),
        // Uncomment to assert the exact sequence of emitted states
        // (check the guards first — a conditional emit doesn't always run):
        // expect: () => [isA<CategoryState>()],
        verify: (bloc) {
          verify(
            () => mockCategoryRepository.createCategory(any()),
          ).called(greaterThanOrEqualTo(1));
          verify(
            () => mockCategoryRepository.fetchCategories(),
          ).called(greaterThanOrEqualTo(1));
          expect(bloc.state.errorMessage, isNull);
          expect(bloc.state.successMessage, isNotNull);
        },
      );

      blocTest<CategoryBloc, CategoryState>(
        'CategoryCreated surfaces an error when a dependency fails',
        setUp: () {
          // Make every dependency call this action performs
          // fail, replacing the stubs from setUp().
          when(
            () => mockCategoryRepository.createCategory(any()),
          ).thenThrow(const ServerException(message: 'test'));
          when(
            () => mockCategoryRepository.fetchCategories(),
          ).thenThrow(const ServerException(message: 'test'));
        },
        build: buildCategoryBloc,
        act: (bloc) => bloc.add(const CategoryCreated('')),
        verify: (bloc) {
          expect(bloc.state.errorMessage, isNotNull);
          expect(bloc.state.successMessage, isNull);
        },
      );
    });
  });
}
